ignore:
  - package:
      name: anchore/scan-action
  - package:
      location: "/root/.terraform.d/plugins/linux_amd64/terraform-provider-**"
  - package:
      location: "/usr/bin/terraform"
  - package:
      location: "/usr/local/bin/terraform"
  - vulnerability: GHSA-fw7p-63qq-7hpr # filippo.io/edwards25519 -> FP, not present in binary dependencies
exclude:
  - './.github/scripts/**' # test files